---
title: "Exercice2"
format: html
editor: visual
---

## 3. Quels fichiers sont présents à la racine du nouveau projet ? Décrivez.

À la racine du projet, on trouve deux fichiers : un fichier .gitignore, qui sert à ignorer certains fichiers dans le suivi Git, et un fichier .Rproj, qui correspond au projet RStudio et contient sa configuration.

## 4. Modifiez le fichier README.md en ajoutant les instructions suivantes :

Je modifie mon fichier en local !! 


## 5. En utilisant l’éditeur visuel de git sous RStudio, ajoutez le fichier README.md, puis créez votre premier commit avec le message : mon premier commit. Naviguez jusqu’à votre projet sous GitHub. Voyez-vous une différence ? Est-ce normal ?

**Processus** : On coche sur le fichier exercice2 qui est sur le bloc en haut a droite et on clique sur commit. on a ensuite la possibilité de laisser un message. on clique sur bouton commit.
Apres cela, le fichier n'apparait plus dans ce bloc mais seulement dans le bloc de dessous (Files)


**Resultat** : Après avoir effectué le commit, aucune différence n’est visible sur GitHub. Cela est normal car le commit a été réalisé en local. Il faut effectuer un push pour envoyer les modifications vers le dépôt distant afin qu’elles apparaissent sur GitHub.


## 6. Modifiez à nouveau le fichier README.md en ajoutant une nouvelle ligne :

J'écris depuis la branche main.



## 7. Faites un deuxième commit en ajoutant à nouveau le fichier README.md. Ce deuxième commit aura pour message mon deuxième commit. En utilisant le client graphique de RStudio, faites un git push. Que s’est-il passé cette fois-ci sur le dépôt GitHub ?

Après le deuxième commit suivi d’un git push, les modifications sont visibles sur GitHub. Le dépôt distant a été mis à jour avec le fichier README.md et le message de commit "mon deuxième commit" apparaît dans l’historique.


## 8. Créez une nouvelle branche que vous appellerez branche-1. Modifiez le fichier README.md en modifiant la dernière ligne : J'écris depuis la branche-1. Enregistrez vos modifications en faisant un commit de ces modifications.

J'ecris depuis branche-1

## 9. Retournez sur la branche main (ou master), puis faites à nouveau les instructions de la question 8, cette fois-ci en nommant la branche branche-2. Poussez vos modifications sous GitHub avec la commande push. Ouvrez une pull request sur GitHub, puis faites un merge de la branche-2 dans main.



